### ISSUE TITLE
Warn of old Node version

### ISSUE THREAD

**Issue by stevage** [TerriaJS/TerriaMap#11]
When trying to build with Node 0.10.x, an error like this appears:

```
[01:10:27] 'lint' errored after 1.25 ms
[01:10:27] TypeError: undefined is not a function
    at runExternalModule (/home/ubuntu/TerriaMap/node_modules/terriajs/buildprocess/runExternalModule.js:7:18)
    at Gulp.<anonymous> (/home/ubuntu/TerriaMap/gulpfile.js:114:5)
    at module.exports (/home/ubuntu/TerriaMap/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/ubuntu/TerriaMap/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/ubuntu/TerriaMap/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/ubuntu/TerriaMap/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
```

We could detect the version of Node and warn immediately.
